services:
  mongo:
    image: mongo:6
    container_name: code-sync-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - Code-Sync
  server:
    container_name: code-sync-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - Code-Sync
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/code_sync
    depends_on:
      - mongo

  client:
    container_name: code-sync-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - Code-Sync
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  Code-Sync:
    driver: bridge
volumes:
  mongo_data:
